In [1]:
import pandas as pd

In [2]:
# initializing 311 service requests data

df = pd.read_csv("raw-data/Department_of_Sanitation_311_Service_Requests20240922.csv")
df.dtypes

Unique Key                          int64
Created Date                       object
Closed Date                        object
Agency                             object
Agency Name                        object
Complaint Type                     object
Descriptor                         object
Location Type                      object
Incident Zip                      float64
Incident Address                   object
Street Name                        object
Cross Street 1                     object
Cross Street 2                     object
Intersection Street 1              object
Intersection Street 2              object
Address Type                       object
City                               object
Landmark                          float64
Facility Type                      object
Status                             object
Due Date                           object
Resolution Action Updated Date     object
Community Board                    object
Borough                            object
X Coordinate (State Plane)        float64
Y Coordinate (State Plane)        float64
Park Facility Name                 object
Park Borough                       object
Vehicle Type                      float64
Taxi Company Borough              float64
Taxi Pick Up Location             float64
Bridge Highway Name               float64
Bridge Highway Direction          float64
Road Ramp                         float64
Bridge Highway Segment            float64
Latitude                          float64
Longitude                         float64
Location                           object
dtype: object

In [3]:
len(df)

3361

In [4]:
# counting data per borough

df["Borough"].value_counts()

Borough
BROOKLYN         1161
QUEENS           1058
MANHATTAN         403
BRONX             396
STATEN ISLAND     328
Unspecified        15
Name: count, dtype: int64

In [5]:
# filtering only Bronx boroughs

bronx_df = df[df["Borough"] == "BRONX"]

In [6]:
# summing up per Community Board

bronx_df["Community Board"].value_counts()

Community Board
12 BRONX             89
10 BRONX             47
09 BRONX             44
11 BRONX             37
04 BRONX             35
06 BRONX             28
05 BRONX             25
07 BRONX             23
03 BRONX             20
08 BRONX             19
01 BRONX             14
02 BRONX             13
Unspecified BRONX     2
Name: count, dtype: int64

In [7]:
# filtering only Bronx community board 1 (Port Morris, Melrose, Mott Haven)

bronx_cb1_df = bronx_df[bronx_df["Community Board"] == "01 BRONX"]

In [8]:
bronx_cb1_df

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
78,23345061,06/01/2012 08:14:00 AM,06/01/2012 12:00:00 PM,DSNY,Department of Sanitation,Sanitation Condition,12 Dead Animals,Sidewalk,10451.0,479 WALTON AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.818133,-73.928505,"(40.818132665666106, -73.92850522614818)"
439,23344349,06/01/2012 03:01:00 PM,06/05/2012 12:00:00 PM,DSNY,Department of Sanitation,Dirty Conditions,E12 Illegal Dumping Surveillance,Sidewalk,10451.0,478 GERARD AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.818100,-73.929575,"(40.81810038718205, -73.9295746654137)"
593,23349562,06/02/2012 09:31:00 AM,06/02/2012 12:00:00 PM,DSNY,Department of Sanitation,Missed Collection (All Materials),1 Missed Collection,Sidewalk,10455.0,2809 3 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.814984,-73.919665,"(40.81498413988062, -73.91966475726944)"
889,23352390,06/03/2012 12:46:00 PM,06/06/2012 12:00:00 PM,DSNY,Department of Sanitation,Dirty Conditions,E12 Illegal Dumping Surveillance,Sidewalk,10454.0,353 EAST 138 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.809701,-73.924288,"(40.809700932747305, -73.92428777837402)"
1354,23354612,06/04/2012 01:01:00 PM,06/04/2012 01:01:00 PM,DSNY,Department of Sanitation,Literature Request,BLUE RECYCLING DECAL,Other,10454.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1356,23356420,06/04/2012 01:01:00 PM,06/04/2012 01:01:00 PM,DSNY,Department of Sanitation,Literature Request,GREEN MIXED PAPER DECALS,Other,10454.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1374,23356183,06/04/2012 01:16:00 PM,06/04/2012 01:16:00 PM,DSNY,Department of Sanitation,Literature Request,RECYCLING CHECKLIST FLYER E/S,Other,10454.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1447,23358532,06/04/2012 03:08:00 PM,06/05/2012 12:00:00 PM,DSNY,Department of Sanitation,Sanitation Condition,15 Street Cond/Dump-Out/Drop-Off,Street,10454.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.805217,-73.925756,"(40.805217007384925, -73.92575580118789)"
2618,23374510,06/06/2012 03:37:00 PM,06/07/2012 12:00:00 PM,DSNY,Department of Sanitation,Sanitation Condition,15 Street Cond/Dump-Out/Drop-Off,Street,10455.0,476 TIMPSON PLACE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.810107,-73.905636,"(40.8101071181397, -73.90563639202513)"
2779,23372875,06/06/2012 11:16:00 PM,06/07/2012 12:00:00 PM,DSNY,Department of Sanitation,Literature Request,DIGEST OF CODES,Other,10451.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2833,23378317,06/07/2012 08:12:00 AM,06/07/2012 12:00:00 PM,DSNY,Department of Sanitation,Sanitation Condition,12 Dead Animals,Sidewalk,10454.0,EAST 138 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.808505,-73.921468,"(40.80850509143969, -73.92146790684019)"
3062,23379920,06/07/2012 12:46:03 PM,06/27/2012 12:00:00 AM,DSNY,Department of Sanitation,Graffiti,Graffiti,Comercial,10451.0,120 EAST 149 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.819014,-73.929082,"(40.819014077062874, -73.92908234368335)"
3067,23378253,06/07/2012 12:49:01 PM,06/27/2012 12:00:00 AM,DSNY,Department of Sanitation,Graffiti,Graffiti,Comercial,10455.0,460 WILLIS AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.813963,-73.919319,"(40.813962862096766, -73.91931917765653)"
3149,23375807,06/07/2012 02:39:26 PM,07/02/2012 12:00:00 AM,DSNY,Department of Sanitation,Graffiti,Graffiti,Comercial,10455.0,723 WESTCHESTER AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.817573,-73.905955,"(40.81757302310581, -73.90595457282751)"

In [9]:
# Wait... Why are they all from 2012?

In [10]:
df["Created Date"].max()

'06/07/2012 12:55:59 PM'